### ISSUE TITLE
First line of log does not comply to timbre settings

### ISSUE THREAD

**Issue by elisehuard** [fzakaria/slf4j-timbre#21]
Hi, I'm running jetty with timbre for logging and slf4j-timbre to be able to handle other libraries' messages.
Versions:

```
[com.taoensso/timbre "4.5.1"]
[com.fzakaria/slf4j-timbre "0.3.2"]
[org.slf4j/jul-to-slf4j  "1.7.21"]
[org.slf4j/jcl-over-slf4j "1.7.21"]
[org.slf4j/log4j-over-slf4j "1.7.21"]
[ring/ring-jetty-adapter "1.3.2"]
```

It works fine - except for the very first log line, which completely ignores my timbre settings (see first line below).

```
16-07-15 14:54:16 jenglot DEBUG [org.eclipse.jetty.util.log:89] - Logging to com.github.fzakaria.slf4j.timbre.TimbreLoggerAdapter@7c20cdd0 via org.eclipse.jetty.util.log.Slf4jLog
16-07-15 14:54:16,767 INFO [org.eclipse.jetty.server.Server:74] - jetty-7.6.13.v20130916
16-07-15 14:54:16,786 INFO [org.eclipse.jetty.server.AbstractConnector:74] - Started SelectChannelConnector@0.0.0.0:3001
```

My main function goes like this:

```
(defn -main
  [& args]
  ;; set up log format
  (log/merge-config! log-config)

  ;; https://stuartsierra.com/2015/05/27/clojure-uncaught-exceptions
  (Thread/setDefaultUncaughtExceptionHandler
   (reify Thread$UncaughtExceptionHandler
     (uncaughtException [_ thread ex]
       (log/error ex))))

  (jetty/run-jetty app {:port 3001}))
```

So you see, in theory the very first line merges my timbre config.
I can work around it (by doing some logstash foo) but I thought I'd let you know, since it looks like a slf4j-timbre output

**Comment by rufoa** [comment]
That's curious - I'll look into the problem asap

**Comment by rufoa** [comment]
It looks like this isn't a problem with slf4j-timbre.

The `DEBUG` line is emitted in response to you `:require`ing jetty, rather than in response to the contents of your `-main` fn — and because your call to `merge-config!` hasn't yet happened at this point, your custom timbre config isn't in effect.

(Clojure's `require` fn causes the `ring.adapter.jetty` class to undergo static initialisation. This process eventually creates an instance of the slf4j-timbre logger and [emits the `DEBUG` entry you're seeing](https://github.com/eclipse/jetty.project/blob/cd39fd84fe7c61267a5f652a79279b73a10e7f9c/jetty-util/src/main/java/org/eclipse/jetty/util/log/Log.java#L176).)

So if you need to suppress this log entry then you'll have to do it some other way, perhaps using JVM properties or the `TIMBRE_LEVEL` env var (?)

Hope this helps

**Comment by fzakaria** [comment]
Can we close this?

**Comment by rufoa** [comment]
Think so. Please reopen if necessary @elisehuard
