### ISSUE TITLE
java exception's stack trace not displayed

### ISSUE THREAD

**Issue by geekingfrog** [fzakaria/slf4j-timbre#22]
In java code I have the following:
```java
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

public final class Boom {

  private static final Log LOG = LogFactory.getLog(Boom.class);

  public static void boom() throws Exception {
    try {
      throw new Exception("BoomException");
    } catch (Exception e) {
      LOG.error("Got an exception: ", e);
    }
  }
}
```
When running this without `slf4j-timbre` I get the full stack trace in the logs, but with `slf4j-timbre`, I only get the first line:

```
17-01-20 12:02:50 host ERROR [Boom:209] - Got an exception:
```

I tried adding a timbre middleware to inspect the data and it seems the error object is missing altogether.
I've created a repo with a minimal example displaying the issue: https://github.com/geekingfrog/slf4j-timbre-issue

**Comment by rufoa** [comment]
Thanks for the report and test case. I've reproduced this behaviour locally and will look into it ASAP

**Comment by rufoa** [comment]
Cause:
- the [`differentiatedLog` method](https://github.com/qos-ch/slf4j/blob/master/log4j-over-slf4j/src/main/java/org/apache/log4j/Category.java#L189) in `log4j-over-slf4j` is incorrectly taking the `else` branch because `locationAwareLogger` is null
- this means the `Throwable t` is not being passed to our slf4j implementation

What we need to do to fix this:
- `slf4j-timbre.adapter` should implement `org.slf4j.spi.LocationAwareLogger` rather than `org.slf4j.Logger`
- this means adding a new public method [`log`](https://github.com/qos-ch/slf4j/blob/master/slf4j-api/src/main/java/org/slf4j/spi/LocationAwareLogger.java#L60)

**Comment by rufoa** [comment]
[Work so far](https://github.com/fzakaria/slf4j-timbre/compare/master...issue-22)

**Comment by geekingfrog** [comment]
With the `0.3.3` version it works properly. Just need to publish that on clojar.
Thanks for the quick fix.

**Comment by rufoa** [comment]
no problem @geekingfrog (please upgrade to 0.3.4)
