### ISSUE TITLE
Cannot use with jboss owing to nil assertion on arg-array

### ISSUE THREAD

**Issue by lorddoig** [fzakaria/slf4j-timbre#25]
When trying to use with immutant, directing logs to slf4j and then slf4j-timbre, it silently fails and starts printing default output to `stdout`.  After a fair amount of assistance from @tobias, he discovered that the logging subsystem init was failing because of this assertion: https://github.com/fzakaria/slf4j-timbre/tree/master/src/slf4j_timbre/adapter.clj#L95 and then defaulting to something else.  Removing this assertion correctly directs logs to timbre as desired.  

Opening as an issue instead of a PR because I'm not sure if that assertion is important for other use cases.

**Comment by rufoa** [comment]
That assertion was a reminder because I hadn't yet written the code for properly handling a non-nil `arg-array`. Sorry if it was difficult to identify the root cause.

I've pushed a new snapshot to [clojars](https://clojars.org/com.fzakaria/slf4j-timbre/versions/0.3.6-SNAPSHOT) as `[com.fzakaria/slf4j-timbre "0.3.6-SNAPSHOT"]`. Please try it out and let me know if it works for you.

Specifically, please confirm that the filename and line number reported in the stack trace is correct (i.e. points to the actual `throw` and not to some slf4j logging adapter code).

**Comment by tobias** [comment]
Thanks @rufoa! This allows timbre to work in my simple test app when I depend on 0.3.6-SNAPSHOT and force jboss-logging to use slf4j with `:jvm-opts ["-Dorg.jboss.logging.provider=slf4j"]` in `project.clj`. I haven't yet tested with an exception - I'll need to figure out how to get something that uses jboss-logging to throw and report an error.

**Comment by rufoa** [comment]
> I'll need to figure out how to get something that uses jboss-logging to throw and report an error.

Don't worry about it, looks like there was indeed a bug in the previous snapshot but I've fixed it now

Pushed to clojars as `[com.fzakaria/slf4j-timbre "0.3.6"]`

Thanks for the bug report guys 👍
