### ISSUE TITLE
Choice of two errors, no errors is not an option

### ISSUE THREAD

**Issue by krestivo-kdinfotech** [fzakaria/slf4j-timbre#34]
With this:

```clojure
;; ...
                  [com.fzakaria/slf4j-timbre "0.3.13"]
                   [com.taoensso/timbre "4.10.0"]
                     [org.slf4j/slf4j-log4j12 "1.7.26"]
```

I get

```
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

OK... if I add this, though:

```clojure
;; ...
                [com.fzakaria/slf4j-timbre "0.3.13"]
                   [com.taoensso/timbre "4.10.0"]
                     [org.slf4j/slf4j-log4j12 "1.7.26"]
                 [org.slf4j/log4j-over-slf4j "1.7.14"]

```

Then the whole compile fails, with:

```
							 PatternLayout.TTCC_CONVERSION_PATTERN);
							              ^
  symbol:   variable TTCC_CONVERSION_PATTERN
  location: class PatternLayout

```

From a .java source file vendored dependency that does its own log4j logging.

In both cases, lein tree shows that  this does include

```clojure
 [log4j "1.2.17"]
```

as a transitive dependency.

I could edit the java dep but will probably just limp along with the apache error instead.

**Comment by rufoa** [comment]
Thanks for the report. I'm still trying to figure out what's going on here, but a few points spring to mind.

- It's probably wrong to use `slf4j-log4j12` and `log4j-over-slf4j` at the same time ([reference](https://www.slf4j.org/legacy.html#log4jRecursion))
- If you want your logs to go `log4j --> slf4j --> timbre` you would normally just use `log4j-over-slf4j` and `slf4j-timbre` (not `slf4j-log4j12`, which goes the wrong way)
- It seems as though the `log4j-over-slf4j` bridge only provides a stub of the `org.apache.log4j.PatternLayout` class (this seems to be a [known inadequacy](https://www.slf4j.org/legacy.html#losFail))
- Normally you would use your build tool to deliberately exclude the `log4j` dependency when you swap in the `log4j-over-slf4j` bridge because it provides the same classes

**Comment by krestivo-kdinfotech** [comment]
Thanks, it seems the root cause is the java file making direct calls to log4j as in the known inadequacy you helpfully provided in your link. Nothing I can do about that; can't use timbre for this project. Closing. Thanks again.
